# Generated by Django 3.2.2 on 2021-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Growth', 'Growth'), ('Bussiness', 'Bussiness')], max_length=200),
        ),
    ]
