# Generated by Django 3.2.2 on 2021-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210510_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bussiness', 'Bussiness'), ('Growth', 'Growth')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
