# Generated by Django 3.2.2 on 2021-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210528_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Growth', 'Growth'), ('Bussiness', 'Bussiness'), ('Others', 'Others')], max_length=200),
        ),
    ]
