# Generated by Django 3.2.2 on 2021-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210528_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Others', 'Others'), ('Bussiness', 'Bussiness'), ('Growth', 'Growth')], max_length=200),
        ),
    ]
